version: '3'
services:
  db:
    build:
        context: .
        dockerfile: db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - .pgdata:/var/lib/postgresql/data
    
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
 
